export const PAYROLL_RUN_REPOSITORY = Symbol('PAYROLL_RUN_REPOSITORY');
export const PAYROLL_RUN_LINE_REPOSITORY = Symbol('PAYROLL_RUN_LINE_REPOSITORY');
export const PAYROLL_RUN_LINE_COMPONENT_REPOSITORY = Symbol('PAYROLL_RUN_LINE_COMPONENT_REPOSITORY');
export const PAYSLIP_REPOSITORY = Symbol('PAYSLIP_REPOSITORY');
export const PAYSLIP_LINE_REPOSITORY = Symbol('PAYSLIP_LINE_REPOSITORY');
export const TAX_SLAB_GROUP_REPOSITORY = Symbol('TAX_SLAB_GROUP_REPOSITORY');
export const TAX_SLAB_REPOSITORY = Symbol('TAX_SLAB_REPOSITORY');
