export const CLOCK_EVENT_REPOSITORY = Symbol('CLOCK_EVENT_REPOSITORY');
export const TIME_ENTRY_REPOSITORY = Symbol('TIME_ENTRY_REPOSITORY');
export const TIMESHEET_REPOSITORY = Symbol('TIMESHEET_REPOSITORY');
