export const PAY_COMPONENT_REPOSITORY = Symbol('PAY_COMPONENT_REPOSITORY');
export const SALARY_STRUCTURE_REPOSITORY = Symbol('SALARY_STRUCTURE_REPOSITORY');
export const SALARY_STRUCTURE_COMPONENT_REPOSITORY = Symbol('SALARY_STRUCTURE_COMPONENT_REPOSITORY');
export const SALARY_REVISION_REPOSITORY = Symbol('SALARY_REVISION_REPOSITORY');
export const BONUS_AWARD_REPOSITORY = Symbol('BONUS_AWARD_REPOSITORY');
