export const LEAVE_TYPE_REPOSITORY = Symbol('LEAVE_TYPE_REPOSITORY');
export const LEAVE_BALANCE_REPOSITORY = Symbol('LEAVE_BALANCE_REPOSITORY');
export const LEAVE_REQUEST_REPOSITORY = Symbol('LEAVE_REQUEST_REPOSITORY');
export const HOLIDAY_CALENDAR_REPOSITORY = Symbol('HOLIDAY_CALENDAR_REPOSITORY');
export const HOLIDAY_REPOSITORY = Symbol('HOLIDAY_REPOSITORY');
