export const EMPLOYEE_ASSESSMENT_REPOSITORY = Symbol('EMPLOYEE_ASSESSMENT_REPOSITORY');
export const EMPLOYEE_DOCUMENT_LINK_REPOSITORY = Symbol('EMPLOYEE_DOCUMENT_LINK_REPOSITORY');
export const EMPLOYEE_HR_RECORD_REPOSITORY = Symbol('EMPLOYEE_HR_RECORD_REPOSITORY');
export const EMPLOYEE_ONBOARDING_TASK_REPOSITORY = Symbol('EMPLOYEE_ONBOARDING_TASK_REPOSITORY');
