export const EMPLOYEE_REPOSITORY = Symbol('EMPLOYEE_REPOSITORY');
export const EMPLOYEE_PROFILE_REPOSITORY = Symbol('EMPLOYEE_PROFILE_REPOSITORY');
export const EMPLOYEE_PERSONAL_DETAILS_REPOSITORY = Symbol('EMPLOYEE_PERSONAL_DETAILS_REPOSITORY');
export const EMPLOYEE_EDUCATION_REPOSITORY = Symbol('EMPLOYEE_EDUCATION_REPOSITORY');
export const EMPLOYEE_WORK_HISTORY_REPOSITORY = Symbol('EMPLOYEE_WORK_HISTORY_REPOSITORY');
export const EMPLOYEE_SEPARATION_REPOSITORY = Symbol('EMPLOYEE_SEPARATION_REPOSITORY');
export const EMPLOYEE_EXIT_INTERVIEW_REPOSITORY = Symbol('EMPLOYEE_EXIT_INTERVIEW_REPOSITORY');
export const EMPLOYEE_OFFBOARDING_TASK_REPOSITORY = Symbol('EMPLOYEE_OFFBOARDING_TASK_REPOSITORY');
